// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3935Xhj5a_VXXAdIpM2FWqnn48E5c5Jc',
    appId: '1:216694879990:web:c0d6225f5a51536d395ed7',
    messagingSenderId: '216694879990',
    projectId: 'newsphere-da26c',
    authDomain: 'newsphere-da26c.firebaseapp.com',
    storageBucket: 'newsphere-da26c.appspot.com',
    measurementId: 'G-6SLVDFM5Y8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbc9Rlob18OYK6LFR8KKyz8DhhU9YdVZM',
    appId: '1:216694879990:android:8bb7bbb8e037ce73395ed7',
    messagingSenderId: '216694879990',
    projectId: 'newsphere-da26c',
    storageBucket: 'newsphere-da26c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8ceMEFWkS6Y-rgecYVvdcG7GlIFAHyQA',
    appId: '1:216694879990:ios:fb80449c86330711395ed7',
    messagingSenderId: '216694879990',
    projectId: 'newsphere-da26c',
    storageBucket: 'newsphere-da26c.appspot.com',
    iosBundleId: 'com.example.newssphere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8ceMEFWkS6Y-rgecYVvdcG7GlIFAHyQA',
    appId: '1:216694879990:ios:fb80449c86330711395ed7',
    messagingSenderId: '216694879990',
    projectId: 'newsphere-da26c',
    storageBucket: 'newsphere-da26c.appspot.com',
    iosBundleId: 'com.example.newssphere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3935Xhj5a_VXXAdIpM2FWqnn48E5c5Jc',
    appId: '1:216694879990:web:f999461f5d9ed260395ed7',
    messagingSenderId: '216694879990',
    projectId: 'newsphere-da26c',
    authDomain: 'newsphere-da26c.firebaseapp.com',
    storageBucket: 'newsphere-da26c.appspot.com',
    measurementId: 'G-FSLRGHTG0T',
  );

}